-- Drop existing tables if they exist to ensure a clean slate
DROP TABLE IF EXISTS public.live_streams CASCADE;
DROP TABLE IF EXISTS public.vod_streams CASCADE;
DROP TABLE IF EXISTS public.series CASCADE;
DROP TABLE IF EXISTS public.live_categories CASCADE;
DROP TABLE IF EXISTS public.vod_categories CASCADE;
DROP TABLE IF EXISTS public.series_categories CASCADE;

-- Tabela para categorias de canais ao vivo
CREATE TABLE public.live_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT REFERENCES public.xtream_connections(id) ON DELETE CASCADE,
    category_id TEXT NOT NULL,
    category_name TEXT,
    parent_id INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(connection_id, category_id)
);

-- Tabela para categorias de VOD
CREATE TABLE public.vod_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT REFERENCES public.xtream_connections(id) ON DELETE CASCADE,
    category_id TEXT NOT NULL,
    category_name TEXT,
    parent_id INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(connection_id, category_id)
);

-- Tabela para categorias de Séries
CREATE TABLE public.series_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT REFERENCES public.xtream_connections(id) ON DELETE CASCADE,
    category_id TEXT NOT NULL,
    category_name TEXT,
    parent_id INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(connection_id, category_id)
);

-- Tabela para streams de canais ao vivo
CREATE TABLE public.live_streams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT REFERENCES public.xtream_connections(id) ON DELETE CASCADE,
    stream_id INT NOT NULL,
    "name" TEXT,
    stream_icon TEXT,
    category_id TEXT,
    epg_channel_id TEXT,
    added TEXT,
    is_adult TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(connection_id, stream_id)
);

-- Tabela para streams de VOD (Filmes)
CREATE TABLE public.vod_streams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT REFERENCES public.xtream_connections(id) ON DELETE CASCADE,
    stream_id INT NOT NULL,
    "name" TEXT,
    stream_icon TEXT,
    category_id TEXT,
    rating TEXT,
    added TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(connection_id, stream_id)
);

-- Tabela para Séries
CREATE TABLE public.series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT REFERENCES public.xtream_connections(id) ON DELETE CASCADE,
    series_id INT NOT NULL,
    "name" TEXT,
    cover TEXT,
    plot TEXT,
    "cast" TEXT,
    director TEXT,
    genre TEXT,
    release_date TEXT,
    last_modified TEXT,
    rating TEXT,
    category_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(connection_id, series_id)
);